# Generated by Django 4.2 on 2024-08-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment_author_product_author_product_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_users',
        ),
    ]
