# Generated by Django 4.2 on 2024-08-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment_author_product_author_product_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
