# Generated by Django 4.2 on 2024-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_hashtag_product_hashtags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("판매중", "판매중"),
                    ("판매완료", "판매완료"),
                    ("예약중", "예약중"),
                ],
                default="판매중",
                max_length=10,
            ),
        ),
    ]
